// Generated by tools/generate-penalty-sfx.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

extern const int16_t penalty_sfx_kick_pcm[];
extern const size_t penalty_sfx_kick_pcm_samples;
extern const int16_t penalty_sfx_save_pcm[];
extern const size_t penalty_sfx_save_pcm_samples;
extern const int16_t penalty_sfx_goal_pcm[];
extern const size_t penalty_sfx_goal_pcm_samples;
