#!/usr/bin/env python3
"""Convert approved PNG layers to direct Flash RGB565/RGB565A8 (Pillow offline only)."""
import argparse
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/images/penalty/gameplay-v2'


def pixels(path, size, alpha):
    with Image.open(path) as image:
        if image.size != size:
            raise ValueError(f'{path.name}: expected {size}, got {image.size}')
        rgba = image.convert('RGBA')
        rgb = bytearray()
        mask = bytearray()
        raw = rgba.tobytes()
        for r, g, b, a in zip(raw[0::4], raw[1::4], raw[2::4], raw[3::4]):
            value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            rgb.extend((value & 255, value >> 8))
            # Quantize only near-transparent/near-opaque noise, retain real edge alpha.
            mask.append(0 if a <= 1 else 255 if a >= 254 else a)
        if alpha and (min(mask) != 0 or max(mask) != 255):
            raise ValueError(f'{path.name}: missing transparent exterior or opaque interior')
        return bytes(rgb + mask) if alpha else bytes(rgb)


def generate():
    groups = [('background', [('background-240x240.png', 240, 240)], False),
              ('striker', [(f'striker-{i}-88x88.png', 88, 88) for i in range(5)], True),
              ('blue_striker', [(f'blue-striker-{i}-88x88.png', 88, 88) for i in range(9)], True),
              ('keeper', [(f'keeper-{i}-56x56.png', 56, 56) for i in range(7)], True),
              ('balls', [(f'ball-{s}.png', s, s) for s in (18, 16, 14, 12, 10, 8)], True)]
    header = ['/* Generated by tools/convert-penalty-gameplay.py. */', '#pragma once', '#include "lvgl.h"']
    source = ['/* Generated by tools/convert-penalty-gameplay.py; do not edit. */', '#include "gameplay_assets.h"']
    total = 0
    for group, files, alpha in groups:
        descriptors = []
        for i, (file, w, h) in enumerate(files):
            data = pixels(ASSETS / file, (w, h), alpha)
            total += len(data)
            name = f'pixels_{group}_{i}'
            source.append(f'_Alignas(4) static const uint8_t {name}[{len(data)}] = {{')
            source.extend('    ' + ','.join(f'0x{x:02x}' for x in data[j:j+32]) + ','
                          for j in range(0, len(data), 32))
            source.append('};')
            cf = 'LV_COLOR_FORMAT_RGB565A8' if alpha else 'LV_COLOR_FORMAT_RGB565'
            descriptors.append('{.header={.magic=LV_IMAGE_HEADER_MAGIC, .cf=' + cf +
                               f', .w={w}, .h={h}, .stride={w*2}' + '}, ' +
                               f'.data_size={len(data)}, .data={name}' + '}')
        suffix = '' if group == 'background' else f'[{len(files)}]'
        symbol = f'penalty_art_{group}{suffix}'
        header.append(f'extern const lv_image_dsc_t {symbol};')
        value = descriptors[0] if group == 'background' else '{\n    ' + ',\n    '.join(descriptors) + '\n}'
        source.append(f'const lv_image_dsc_t {symbol} = {value};')
    return {'gameplay_assets.h': '\n'.join(header) + '\n',
            'gameplay_assets.c': '\n'.join(source) + '\n'}, total


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files, total = generate()
    for name, content in files.items():
        path = ASSETS / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Outdated generated asset: {name}')
        else:
            path.write_text(content)
    print(f'Penalty art: {total} read-only pixel bytes; ' + ('reproducible PASS' if args.check else 'converted'))


if __name__ == '__main__':
    main()
