#!/usr/bin/env python3
"""Build the approved cover into native RGB565 C data (Pillow required only here)."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/images/penalty'


def main():
    source = Image.open(ASSETS / 'cover-source.png').convert('RGB')
    if source.width * 4 != source.height * 3:
        raise ValueError('Cover source must have the approved 3:4 aspect ratio')
    # Deterministic asset conversion, not runtime scaling/decoding.
    cover = source.resize((240, 320), Image.Resampling.NEAREST)
    cover.save(ASSETS / 'cover-240x320.png')
    rgb = cover.tobytes()
    pixels = [(r >> 3) << 11 | (g >> 2) << 5 | b >> 3
              for r, g, b in zip(rgb[0::3], rgb[1::3], rgb[2::3])]
    rows = [', '.join(f'0x{p:04x}' for p in pixels[i:i + 16]) for i in range(0, len(pixels), 16)]
    data = ('/* Generated by tools/convert-penalty-cover.py; do not edit. */\n'
            '#include <stdint.h>\n'
            'const uint16_t penalty_cover_pixels[240 * 320] = {\n    '
            + ',\n    '.join(rows) + '\n};\n')
    (ASSETS / 'cover_rgb565.c').write_text(data)
    print(f'Cover: 240 x 320 RGB565, {len(pixels) * 2} bytes in read-only Flash')


if __name__ == '__main__':
    main()
