#!/usr/bin/env python3
"""Generate small, deterministic 16 kHz mono PCM effects for Penalty."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

RATE = 16_000
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "assets" / "music" / "penalty"


def noise(count: int, seed: int) -> list[float]:
    values: list[float] = []
    state = seed
    for _ in range(count):
        state ^= (state << 13) & 0xFFFFFFFF
        state ^= state >> 17
        state ^= (state << 5) & 0xFFFFFFFF
        state &= 0xFFFFFFFF
        values.append(((state & 0xFFFF) / 32767.5) - 1.0)
    return values


def quantize(values: list[float], peak: int = 9_000) -> list[int]:
    maximum = max(abs(value) for value in values) or 1.0
    scale = peak / maximum
    result = [int(round(max(-32768, min(32767, value * scale)))) for value in values]
    result[0] = result[-1] = 0
    return result


def kick() -> list[int]:
    count = RATE * 80 // 1000
    grit = noise(count, 0x50454E41)
    values = []
    phase = 0.0
    for i in range(count):
        t = i / RATE
        x = i / (count - 1)
        frequency = 125 - 65 * x
        phase += 2 * math.pi * frequency / RATE
        envelope = math.exp(-6.0 * x) * min(1.0, i / 12)
        values.append(envelope * (math.sin(phase) + 0.36 * grit[i]))
    return quantize(values, 10_000)


def save() -> list[int]:
    count = RATE * 100 // 1000
    grit = noise(count, 0x53415645)
    values = []
    filtered = 0.0
    for i in range(count):
        x = i / (count - 1)
        filtered = filtered * 0.72 + grit[i] * 0.28
        envelope = math.exp(-4.5 * x) * min(1.0, i / 10)
        thump = math.sin(2 * math.pi * 78 * i / RATE)
        values.append(envelope * (0.58 * thump + 0.82 * filtered))
    return quantize(values, 8_500)


def goal() -> list[int]:
    count = RATE * 110 // 1000
    grit = noise(count, 0x474F414C)
    values = []
    filtered = 0.0
    for i in range(count):
        x = i / (count - 1)
        filtered = filtered * 0.45 + grit[i] * 0.55
        attack = min(1.0, i / 24)
        envelope = attack * (1.0 - x) ** 1.6
        pulse = math.sin(2 * math.pi * (175 + 85 * x) * i / RATE)
        values.append(envelope * (0.45 * pulse + 0.55 * filtered))
    return quantize(values, 7_500)


def format_array(name: str, values: list[int]) -> str:
    lines = []
    for offset in range(0, len(values), 12):
        lines.append("    " + ", ".join(str(value) for value in values[offset:offset + 12]) + ",")
    return (
        f"const int16_t {name}[] = {{\n" + "\n".join(lines) + "\n};\n"
        f"const size_t {name}_samples = sizeof({name}) / sizeof({name}[0]);\n"
    )


def generated_files() -> tuple[str, str]:
    header = """// Generated by tools/generate-penalty-sfx.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

extern const int16_t penalty_sfx_kick_pcm[];
extern const size_t penalty_sfx_kick_pcm_samples;
extern const int16_t penalty_sfx_save_pcm[];
extern const size_t penalty_sfx_save_pcm_samples;
extern const int16_t penalty_sfx_goal_pcm[];
extern const size_t penalty_sfx_goal_pcm_samples;
"""
    source = """// Generated by tools/generate-penalty-sfx.py. Do not edit.
// Original synthesized effects: CC0-1.0. 16 kHz, signed 16-bit, mono PCM.
#include "penalty_sfx_pcm.h"

"""
    source += format_array("penalty_sfx_kick_pcm", kick()) + "\n"
    source += format_array("penalty_sfx_save_pcm", save()) + "\n"
    source += format_array("penalty_sfx_goal_pcm", goal())
    return header, source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    header, source = generated_files()
    expected = {
        OUT_DIR / "penalty_sfx_pcm.h": header,
        OUT_DIR / "penalty_sfx_pcm.c": source,
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in expected.items()
                 if not path.exists() or path.read_text() != content]
        if stale:
            parser.error("stale generated files: " + ", ".join(stale))
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
